/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package spglib;

public class spglibJNI {
  public final static native void spg_show_symmetry(long jarg1, long jarg2, long jarg3, int jarg4, double jarg5);
  public final static native int spg_find_primitive(long jarg1, long jarg2, long jarg3, int jarg4, double jarg5);
  public final static native int spg_get_international(String jarg1, long jarg2, long jarg3, long jarg4, int jarg5, double jarg6);
  public final static native long getVectsArray();
  public final static native void putInDoubleNby3Array(long jarg1, int jarg2, int jarg3, double jarg4);
  public final static native double getFromDoubleNby3Array(long jarg1, int jarg2, int jarg3);
  public final static native void deleteIntArray(long jarg1);
  public final static native void deleteDoubleNby3Array(long jarg1);
  public final static native long getPositionsArray(int jarg1);
  public final static native long getTypesArray(int jarg1);
  public final static native int getFromIntArray(long jarg1, int jarg2);
  public final static native void putInIntArray(long jarg1, int jarg2, int jarg3);
}
